version: "1"
rules:
  - base: update-from-upstream
    upstream: mlec1/docker-machine-driver-exo2:main    # the owner of upstream repo
    mergeMethod: rebase
    mergeUnstable: false
  - base: update-from-upstream
    upstream: main
    assignees: # Optional
      - berishaerblin
      - mlec1
      - red667
    reviewers: # Optional
      - berishaerblin
      - mlec1
      - red667
    conflictReviewers: # Optional, on merge conflict assign a reviewer
      - berishaerblin
      - mlec1
      - red667