name: Sync Fork

on:
  schedule:
    - cron: '*/1 * * * *' # every 30 minutes
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v2.0.10
        with:
          owner: mlec1
          repo: docker-machine-driver-exo2
          base: main
          head: main
          token: ${{ secrets.PERSONAL_TOKEN }}
          merge_method: rebase
          auto_approve: true